### ISSUE TITLE
Mergeable histogram?

### ISSUE THREAD

**Issue by Sytten** [cafaro/UDDSketch#1]
Reading the paper, it doesn't say if it is mergeable and, if so, how to merge it. I believe they are not since the gamma parameter is changed when collapsing occurs. So the only way to merge it would be to collapse the other histogram to the same gamma so the buckets become mergable. This seems problematic to me in case of a distributed system, so I would gladly have your take on it.

**Comment by cafaro** [comment]
Thank you very much for your interest in UDDSketch.

UDDSketch is indeed mergeable. You can immediately download and try a corresponding parallel implementation of UDDSketch here: https://github.com/cafaro/PUDDSKETCH.

In the following, I will use latex to typeset formulas.

For both a parallel and a distributed system, without loss of generality, we can assume that the final values of $\gamma$ for two sketches to be merged are the same. In fact, it can be easily proved that this is not restrictive. Setting the same initial $\gamma$ for the two sketches, say $\gamma = \gamma_0$ and the same limit on the number of buckets, the sequence of values that $\gamma$ can assume due to collapses of the two sketches is the same, i.e., $\gamma \in \{\gamma_0, \gamma^2_0, \gamma^4_0, \gamma^8_0 \ldots\}$ holds for both the sketches. If the final values of $\gamma$ do not match, as you observed one can always repeatedly collapse the sketch with smaller $\gamma$ until it matches the $\gamma$ of the other sketch. 

Is this really practical ? Well, in our tests made on several different distributions, we have compared our parallel UDDSketch versus a corresponding parallel implementation of DDsketch, and we have experimentally found that under the same conditions parallel UDDSketch can process its input distributions using at most 5 collapses, whilst parallel DDSketch performs on the same distributions up to about 3500 collapses; regarding accuracy, the tests also show that parallel UDDSketch outperforms parallel DDSketch with regard to accuracy whilst the running time is practically identical for both parallel algorithms on up to 512 processes.

A preprint that I coauthored, with title "Data stream fusion for accurate quantile tracking and analysis", will be available next week on arXiv (https://arxiv.org/list/cs.DS/recent). In this paper we show how to merge two UDDSketch data structures, formally prove that UDDSketch is mergeable, analyze it and provide experimental results. If you are interested to the detail, you can search and download the paper in a few days; it should be available on January 19 2021.

With kind regards,
Massimo Cafaro

**Comment by Sytten** [comment]
Thanks a lot for the prompt response. I am working on a go implementation in the repository https://github.com/GraphMetrics/ddsketch-go (I started from the official ddsketch implementation).

For my use case I believe it will be very common to have different gamma since I collect histograms once per minute, send them to my SaaS and I aggregate them later on different time frame.
I am very interested in UDDsketch, but I will have to see how easy the collapsing can be done in SQL since my repository is based on timescaledb.

I will let you know if I end up using it. If so I will write implementations in Typescript, Ruby, Golang, Python, Java and Rust since those are the targets for our SDK. Happy to collaborate in a more generic implementation if you want to push UDDsketch to the general dev community.

**Comment by cafaro** [comment]
Thank you very much. Scientific code is not, in general, implemented to be as generic as possible. We always focus on the case of maximum interest to us. Anyway, a C++ implementation based on templates should not be particularly difficult.

**Comment by Sytten** [comment]
I proposed that it be implementation in timescale-analytics: https://github.com/timescale/timescale-analytics/issues/41

**Comment by cafaro** [comment]
It would be nice, and useful to a lot of people! Thank you very much.
